[[sec_primitives_strings_re_find]]
=== Searching a String by Pattern
[role="byline"]
by Ryan Neufeld

==== Problem

You need to test a string to see if parts of it match a pattern.

==== Solution

To check for the presence of a pattern inside a string, invoke
+re-find+ with a desired pattern and the string to test. Express the
desired pattern using a regular expression literal (like +#"foo"+ or
++#"\d+"++).

[source,clojure]
----
;; Any contiguous groups of numbers
(re-find #"\d+" "I've just finished reading Fahrenheit 451")
;; -> "451"

(re-find #"Bees" "Beads aren't cheap.")
;; -> nil
----

==== Discussion

+re-find+ is quite handy for quickly testing a string for the presence
of a pattern. It takes a regular expression pattern and a string, then
returns either the first match of that pattern or nil.

If your criterion is more stringent and you require the _entire_
string match a pattern use +re-matches+. Unlike +re-find+,
which matches any portion of a string, +re-matches+ matches if and
only if the *entire* string matches the pattern.

[source,clojure]
----
;; In find, #"\w+" is any contiguous word characters 
(re-find #"\w+" "my-param")
;; -> "my"

;; But in matches #"\w+" means "all word characters"
(re-matches #"\w+" "my-param")
;; -> nil

(re-matches #"\w+" "justLetters")
;; -> "justLetters"
----

==== See Also

* The
  http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html[API
  documentation] for +java.lang.Pattern+, which defines the exact
  regex syntax supported by Java (and Clojure's regular expression literals.)

* <<sec_primitives_strings_re_matches>> for information on extracting
  values from a string using regular expressions.
* <<sec_primitives_strings_find_replace>>
