[[sec_local_io_get_local_resource]]

// Author: John Jacobsen (eigenhombre) (with help from John Cromartie
// (jcromartie) and Alex P (ifesdjeen))

=== Including and Accessing Resource Files in a Clojure Project

==== Problem

You want to include resource files in your project and access them.

==== Solution

Places resource files in the +resources/+ directory at the top level
of your project.

For example, a file +resources/people.edn+:

[source,clojure]
----
[{:first-name "John", :last-name "McCarthy", :language "Lisp"}
 {:first-name "Guido", :last-name "Van Rossum", :language "Python"}
 {:first-name "Rich", :last-name "Hickey", :language "Clojure"}]
----

Use http://clojuredocs.org/clojure_core/clojure.java.io/resource[+clojure.java.io/resource+] to read it.

[source,clojure]
----
(ns process-people
  (:require [clojure.java.io :as io]))

(->> "people.edn"
     io/resource
     slurp
     read-string
     (map :language)))

;; -> (Lisp Python Clojure)
----

==== Discussion

Resources are loaded via the classpath. Leiningen puts the
+resources/+ directory on the classpath automatically; when packaged,
the contents of +resources/+ are copied to the root of the JAR. Data
packaged this way will therefore continue to be available to your code
after your JAR file is distributed.

You can also specify other resource directories using the `:resources-paths` key in your `project.clj`.

[source,clojure]
----
    :resource-paths ["src/main/resources"] ; inside src instead of project root
----
