////
:Author: Eric Normand
:Email: ericwnormand@gmail.com
////

=== Getting set up with lein-cljsbuild

===== Problem

You want to compile ClojureScript to Javascript easily.

===== Solution

Use https://github.com/emezeske/lein-cljsbuild[lein-cljsbuild], a
Leiningen plugin for compiling ClojureScript applications.

In your project.clj:

[source, clojure]
----

:plugins [[lein-cljsbuild "0.3.2"]]

:cljsbuild {:builds [{:source-paths ["src-cljs"]}]}

----

Then, at the command line in your project's directory:

[source, shell]
----
$ lein cljsbuild once

----

The compiler will output to target/cljsbuild-main.js

===== Discussion

https://github.com/emezeske/lein-cljsbuild[lein-cljsbuild] is a
Leiningen plugin for compiling ClojureScript. The first time it is
run, it will fetch and use the ClojureScript compiler and the Google
Closure compiler.

Above, you ran the `once` command to compile the code once. You can
run `auto` to have the plugin automatically recompile whenever the
source files change. For the best development experience, leave `auto`
running while you code. It will output any errors and warnings to the
terminal.

[source, shell]
----

$ lein cljsbuild auto

----

To remove the compiled files generated by lein-cljsbuild, run the
`clean` command:

[source, shell]
----

$ lein cljsbuild clean

----

There are various options for configuring the builds. All of the
options are set in the `:cljsbuild` entry in the project.clj. You can
have multiple builds, each with their own options.

Here is a commented example showing some of the more common
options. This should go in project.clj.

[source, clojure]
----

:cljsbuild {:builds [{:source-paths ["src-cljs"]
                      :compiler {
                        ;; use the externs from jQuery
                        :externs ["externs/jquery-1.9.js"]
                        ;; output the compilation to a different file
                        :output-to "target/main.js"
                        ;; output code in a human-readable indentation
                        :pretty-print true
                        ;; turn on advanced optimizations
                        :optimizations :advanced}}]}

----

===== See Also

* See the https://github.com/emezeske/lein-cljsbuild[lein-cljsbuild] GitHub repository for more commands.
* https://github.com/emezeske/lein-cljsbuild/blob/0.3.2/sample.project.clj[This
sample project.clj file] for information about all of the options.
