[au="Ryan Neufeld"]
=== Changing the capitalization of a string

==== Problem

You need to change the capitalization of a string.

==== Solution

Use +clojure.string/capitalize+ to capitalize the first character in a string.

[source,clojure]
----
(clojure.string/capitalize "this is a proper sentence.")
;; -> "This is a proper sentence."
----

When you need to change the case of all characters in a string use
+clojure.string/lower-case+ or +clojure.string/upper-case+.

[source,clojure]
----
(clojure.string/upper-case "loud noises!")
;; -> "LOUD NOISES!"

(clojure.string/lower-case "COLUMN_HEADER_ONE")
;; -> "column_header_one"
----

==== Discussion

Capitalization functions only affect letters. While the functions
+capitalize+, +lower-case+ and +upper-case+ may modify letters,
characters like punctuation marks, digits or otherwise will remain
untouched.

[source,clojure]
----
(clojure.string/lower-case "!&$#@#%^[]")
;; -> "!&$#@#%^[]"
----

Clojure uses UTF-16 for all strings and as such its definition of what
a letter is is liberal enough to include accented characters. Take for
example the phrase "Hurry up, computer!" which includes the letter
'e' with both acute (é) and circumflex (ê) accents when translated
to French. Since these special characters are considered letters it is
possible for capitalization functions to change case appropriately.

[source,clojure]
----
(clojure.string/upper-case "Dépêchez-vous, l'ordinateur!")
;; -> "DÉPÊCHEZ-VOUS, L'ORDINATEUR!"
----
