=== Changing the Capitalization of a String
[role="byline"]
by Ryan Neufeld

==== Problem

You need to change the capitalization of a string.
((("primitive data", "strings", id="ix_PDstrng", range="startofrange")))(((strings, capitalization of)))((("capitalization, of strings")))

==== Solution

Use +clojure.string/capitalize+ to capitalize the first character in a string:
((("functions", "clojure.string/capitalize")))
[source,clojure]
----
(clojure.string/capitalize "this is a proper sentence.")
;; -> "This is a proper sentence."
----

When you need to change the case of all characters in a string, use
+clojure.string/lower-case+ or +clojure.string/upper-case+:
((("functions", "clojure.string/lower-case")))
[source,clojure]
----
(clojure.string/upper-case "loud noises!")
;; -> "LOUD NOISES!"

(clojure.string/lower-case "COLUMN_HEADER_ONE")
;; -> "column_header_one"
----

==== Discussion

Capitalization functions only affect letters. While the functions
+capitalize+, +lower-case+, and +upper-case+ may modify letters,
characters like punctuation marks or digits will remain
untouched:

[source,clojure]
----
(clojure.string/lower-case "!&$#@#%^[]")
;; -> "!&$#@#%^[]"
----

Clojure uses UTF-16 for all strings, and as such its definition of what
a letter is is liberal enough to include accented characters. Take the phrase, "Hurry up, computer!" which includes the letter
'e' with both acute (_é_) and circumflex (_ê_) accents when translated
to French. Since these special characters are considered letters, it is
possible for capitalization functions to change case appropriately:

[source,clojure]
----
(clojure.string/upper-case "Dépêchez-vous, l'ordinateur!")
;; -> "DÉPÊCHEZ-VOUS, L'ORDINATEUR!"
----

==== See Also

- The +clojure.string+ namespace
  http://bit.ly/clj-string-api[API documentation]

- The +java.lang.String+
  http://bit.ly/javadoc-string[API
  documentation]

