[[sec_webapps__luminus]]
=== Building Applications with Luminus
[role="byline"]
by Dmitri Sotnikov

==== Problem

// RN: The big value proposition here is that Luminus gives a fast path to
// getting a ring/compojure app created and running quickly. Where possible,
// rely on other recipes to explain Luminus-stack tech.

Quickly create a typical Ring/Compojure web application structure, to
get a fast start on a new web development project.

==== Solution

Use the Luminus leiningen template when creating a new project.

At the command line, type:

[source,console]
----
$ lein new luminus myapp
----

This will create a new Ring/Compojure application, with skeletal
namespace and resource directory structure that is ready to be
packaged as standalone +jar+ or a +war+ that can be
deployed on an application server.

You can start the application in development mode by running:

[source,console]
----
$ lein ring server
----

==== Discussion

Luminous doesn't do anything you couldn't do yourself, but provides a
standardized set of libraries and boilerplate for creating common
Ring/Compojure applications.

The template generates a standard directory structure within your
project, defines a main handler for your application, adds +lein-ring+
hooks for it in the _project.clj_, provides a default logging
configuration and sets up the default routes.

You can add additional functionality by specifying profiles when
creating the application, which extend the generated code to include
the relevant stubs. Below are some examples of initializing the
application with a default configurations for different databases.

[source,console]
----
$ lein new luminus app1 +h2

# Or, with PostgreSQL
$ lein new luminus app2 +postgres

# Or, ClojureScript!
$ lein new luminus app3 +cljs

# You can also specify multiple profiles simultaneously:
$ lein new luminus app4 +cljs +postgres
----

The resulting application is structured using the following namespaces.

The +<app-name>.handler+ namespace contains +init+ and +destroy+
functions. These will be called when the application is starting up
and shutting down respectively. It also contains the +app+ handler
function that's used by Ring to initialize the route handlers.

The +<app-name>.routes+ package is used to house the core logic of the
application. Here is where you would define the application routes and
their handlers. The +<app-name>.routes.home+ namespace contains the
routes for the default +/+ and +/about+ pages.

The layout for the site is generated by the +render+ function in the
/<app-name>.views.layout+ namespace.  The HTML templates for the pages
can be found under +src/<app-name>/views/templates/+. Luminus uses
https://github.com/yogthos/Selmer[Selmer] as its default templating
engine.

Any miscellaneous helpers will be found under the
+<app_name>.views.util+ namespace.

When a database profile is selected the +<app_name>.models.db+ and
+<app_name>.models.schema+ namespaces will be created. The +schema+
namespace is reserved for table definitions, while the +db+ namespace
houses the functions dealing with the application model.

The application can be packaged as a standalone _jar_ using *+lein ring uberjar+*, or as a _war_ using *+lein ring uberwar+*.

==== See Also

* To see more details on using Luminus, visit the http://www.luminusweb.net/[Luminus] project page.
