=== Luminus

==== Problem

Create a skeleton web application with the common boilerplate initialized.

==== Solution

Use the +luminus+ template when creating a new project.

----
lein new luminus myapp
----

The above will create a new Ring/Compojure application that is
ready to be packaged for running as a standalone +jar+ or a
+war+ that can be deployed on an application server.

You can start the application in development mode by running:

----
lein ring server
----

The application can be packaged as a standalone +jar+ using:

----
lein ring uberjar
----

To package for deployment as a a +war+ use:

----
lein ring uberwar
----

===== Discussion

Luminus provides a set of libraries and standard boilerplate for
creating common Ring/Compojure applications.

The template generates a handler for your application, adds +lein-ring+ hooks for it in the
+project.cjs+, provides a default logging configuration and sets up the default routes for the application.

We can add additional functionality by specifying profiles when creating the application.
Below we can see examples of initializing the application with a default configurations for
different databases.

----
lein new luminus app1 +h2
----

----
lein new luminus app2 +postgres
----

We can also add support for ClojureScript use the +cljs+ profile.

----
lein new luminus app3 +cljs
----

We can also specify multiple profiles simultaneously:

----
lein new luminus app4 +cljs +postgres
----

The resulting application is structured using the following namespaces.

The +<app-name>.handler+ namespace contains +init+ and +destroy+ functions. These will be called when the
application is starting up and shutting down respectively. It also contains the +app+ handler
function that's used by Ring to initialize the route handlers.

The +<app-name>.routes+ package is used to house the core logic of the application. Here is where you would
define the application routes and their handlers. The +<app-name>.routes.home+ namespace contains the routes for
the defaukt +/+ and +/about+ pages.

The layout for the site is generated by the +render+ function in the /<app-name>.views.layout+ namespace.
The HTML templates for the pages can be found under +src/<app-name>/views/templates/+. Luminus uses
https://github.com/yogthos/Selmer[Selmer] as its default templating engine.

Any miscelaneous helpers will be found under the +<app_name>.views.util+ namespace.

When a database profile is selected the +<app_name>.models.db+ and +<app_name>.models.schema+
namespaces will be created. The +schema+ namespace is reserved for table definitions, while the +db+
namespace houses the functions dealing with the application model.

====== See Also

* To see more details on using Luminus, visit the http://www.luminusweb.net/[Luminus] project page.
