=== Retrieve and parse RSS data

// By Osbert Feng (osbert)

==== Problem

You need to parse RSS data.

==== Solution

Use +feedparser-clj.core/parse-feed+ to parse RSS data from a URL.

[source,clojure]
----

(feedparser-clj.core/parse-feed "https://github.com/clojure-cookbook/clojure-cookbook/commits/master.atom")
;; -> {:authors [...] :entries [{:link "LINK" :title "TITLE" :contents "CONTENT"} {:link ... }] ... }
----

+feedparser-clj.core/parse-feed+ can also be fed a java.io.InputStream to read from a file.

[source,clojure]
----
(with-open [file-stream (clojure.java.io/input-stream "master.atom")]
  (feedparser-clj.core/parse-feed file-stream))
;; -> {:authors [...] :entries [{:link "LINK" :title "TITLE" :contents "CONTENT"} {:link ... }] ... }
----

==== Discussion

+feedparser-clj+ is a wrapper around the Java ROME library which
capable of processing a variety of RSS and Atom versions.
+feedparser-clj.core/parse-feed+ returns a Clojure map that closely
mimics the underlying XML feed.

Most of the time, what you care about will be under the +:entries+ key,
which contains an array of maps corresponding to each RSS entry.

[NOTE] 
ROME returns a com.sun.syndication.feed.synd.SyndFeedImpl
object under the covers, but it is generally preferred to return
Clojure maps (or records) instead of Java objects.

