==== Access MongoDB
// By Tobias Bayer (codebrickie)

===== Problem

You want to access an instance of MongoDB.

===== Solution

Use Monger for connecting to MongoDB and work with the documents in the database.

Include Monger in your project file:

.project.clj
[source,clojure]
----
(defproject mongodb "1.0.0-SNAPSHOT"
              :dependencies [[com.novemberain/monger "1.6.0"]])
----

Assuming your MongoDB instance is running with default parameters, you can connect to it and select the database you want to work with:

[source,clojure]
----
(require '[monger.core :as mg])

(mg/connect!)

(mg/set-db! (mg/get-db "my-db"))
----

Inserting data into a collection is quite easy. In Clojure your data is most likely already represented as a map.

[source,clojure]
----
(require '[monger.collection :as mc])

(insert "musicians" { :first_name "John" :last_name "Lennon" })
----

QUERY DATA (suggest ++find-maps++ for simple further usage of query results)
 - WITHOUT PARAMS (aka "find-all")
 - WITH PARAMS


===== Discussion

NON-STANDARD CONNECT

INSERTING WITH EXPLICIT ID

QUERY OPERATORS

UPDATES

REMOVE DOCUMENTS

DISCONNECT

===== See Also
See the http://clojuremongodb.info[Monger documentation] for more details.
