[[sec_exploring_namespaces]]
=== Exploring Namespaces
[role="byline"]
by John Cromartie

==== Problem

You want to know what namespaces are loaded and what public vars are available inside them.((("development ecosystem", "namespaces")))(((namespaces, basics of)))

==== Solution

Use +loaded-libs+ to obtain the set of currently loaded namespaces. For example, from a REPL:

[source,text]
----
user=> (pprint (loaded-libs))
#{clojure.core.protocols clojure.instant clojure.java.browse
  clojure.java.io clojure.java.javadoc clojure.java.shell clojure.main
  clojure.pprint clojure.repl clojure.string clojure.uuid clojure.walk}
----

Use +dir+ from a REPL to print the public vars in a namespace:

[source,text]
----
user=> (dir clojure.instant)
parse-timestamp
read-instant-calendar
read-instant-date
read-instant-timestamp
validated
----

Use +ns-publics+ to obtain a mapping of symbols to public vars in a namespace:

[source,clojure]
----
(ns-publics 'clojure.instant)
;; -> {read-instant-calendar #'clojure.instant/read-instant-calendar,
;;     read-instant-timestamp #'clojure.instant/read-instant-timestamp,
;;     validated #'clojure.instant/validated,
;;     read-instant-date #'clojure.instant/read-instant-date,
;;     parse-timestamp #'clojure.instant/parse-timestamp}
----

==== Discussion

Namespaces in Clojure are dynamic mappings of symbols to vars. A
namespace is not available until it is required by something else;
for example, when starting a REPL or as a dependency in an +ns+
declaration. Nothing is known about available Clojure libraries and
namespaces until runtime, which is in contrast to typical Java
development (where most everything about a package is known at compile
time).

The downside of this dynamic nature is that you need to at least know
which namespaces to load in order to explore them.

==== See Also

* The +clojure.repl+ http://bit.ly/clj-repl-doc[API documentation]
* <<sec_interactive_docs>>
