==== Reading and writing files

// By Stefan Karlsson (zclj)

===== Problem

You need to read or write a file.

===== Solution

To write to a file use +spit+.

[source,clojure]
----
(spit "stuff.txt" "my stuff")
----

+slurp+ will open a file and read all its contents.

[source,clojure]
----
(slurp "stuff.txt")
;; -> "all my stuff"
----

If required, the encoding to use can be specified with the +:encoding+ option.
[source,clojure]
----
(slurp "stuff.txt" :encoding "UTF-8")
;; -> "all my stuff"
----

Appending to an existing file can be done with +spit+ by using the +:append+ option.
[source,clojure]
----
(spit "stuff.txt" "even more stuff" :append true)
----

When you want to read a file line by line and not all contents at once, use a java.io.Reader.
[source,clojure]
----
(with-open [file (clojure.java.io/reader "stuff.txt")]
  (doseq [line (line-seq file)]
    (println line)))
----

===== Discussion
When using +:append+ text will be appended to the end of the file. If you want the text to be appended to a new line, add a new line +\n+ character at the beginning of the text to append.

The difference between using +slurp+ and +spit+ to using a +java.io.Reader+ or +java.io.Writer+ is that the file remains open when using the Reader/Writer. This can lead to better efficiency if you need to access the file repeatedly.

The +with-open+ macro will make sure that the file is closed when leaving its body.
[source,clojure]
----
(with-open [file (clojure.java.io/writer "stuff.txt")]
  (.write file "soo much stuff"))
----